In [8]:
class A:
    def __init__(self):
        print("hello world")
class B (A):
    def __init__(self):   # constructors will be called automatically
        super().__init__()  # with the help of super keyword i will cal lthe parent class
        print("this is the child")
b=B()

hello world
this is the child


In [25]:
# >> swaping of 2 number <<<<<<<<<<<
a=10
b=20
a,b=b,a   # simply to swqp number in python
print(a)
print(b)

20
10


In [4]:
a={1:{'a':'deepak','surname':'khetwal'},2:{'age':23,12:4}}
print(a[1])
print(a[1].values())  # jaise pehel dictionary 1 ki key a and values deepak hai

{'a': 'deepak', 'surname': 'khetwal'}
dict_values(['deepak', 'khetwal'])


In [31]:
print(a[2])   # by printing this i will get the values

{'age': 23, 12: 4}


In [37]:
print(a[2].keys())   # by printing the keys we will get the keys of all

dict_keys(['age', 12])


In [19]:
#            >>>>>>>>>>>>>>>>>>>>>.   NESTED DICTIONARY  <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<


D={1:{'a':'b',1:2},
   'name':['deepak','khetwal'],
   'insidedictionary':{'b':{'child':'nested'}
                      }
  }

print(D[1])  # this is how it works d ke andar ka 1 dictionary ka value

print(D['insidedictionary']['b'])  # this is how i called the dictionay inside dictionary

print(D['insidedictionary']['b']['child'])   # acessing and taking the values of inside keys
      
print(D['name'])      # this is how i aces the values


2
{'child': 'nested'}
nested
['deepak', 'khetwal']


In [7]:
# finding the higesht and minimumvalues

largest=0
smallest=0
a=[]
while True:
    inputValue=input("enter the value")
    
    if inputValue == "done":
        break
    else:
        try:
            number=int(inputValue)
        except:
            print("NumberException")
        if number >largest:
            
            largest=number
            a.append(largest)
        else:
            a.append(number)   # number will get append
#             largest
print(largest)

print(a)
smallest=a[0]
for i in range(1,len(a)):
    if(a[i]>smallest):
        continue
    else:
        smallest=a[i]
        
                
print(smallest)  
       
      

enter the value23
enter the value4
enter the value2
enter the value3
enter the value4
enter the value300
enter the valuedone
300
[23, 4, 2, 3, 4, 300]
2


In [13]:
# check it some basics concept of dictionary

aa={1:['deepak','khetwal'],2:{'name':'deepak'},3:{34:{3000:400,30:45}}}  # : colon ke left side ka keys n right side ka values always
print(aa)

{1: ['deepak', 'khetwal'], 2: {'name': 'deepak'}, 3: {34: {3000: 400, 30: 45}}}


In [15]:
print(aa[1])
print(aa[3][34][30])   # 3 is a key 34 is another key and  30 is a key
print(aa[2]['name'])

['deepak', 'khetwal']
45
deepak


In [14]:
print(aa[3][34][30])   # nested dictionary

45


In [21]:
print(aa[3].keys())    # to fnd the values dictionary inside the dictionary..yrh 3 is the name of dictionay ,uske andar 34 is a key
print(aa[3].values())    # and  (:) ke baad sabh values hi hai.keys consist of values

dict_keys([34])
dict_values([{3000: 400, 30: 45}])


In [20]:
print(aa[3][34].keys())

dict_keys([3000, 30])


In [4]:
# importatnt concept of 3d  array,as we know one dimentional mean first brackets ke andar[] 2d mean second bracket ke andar value[[values]] first wll be empty and 2nds values
# and for 3rd the third dimentional wil content the values,[[[value]]] ,it mean 1 and 2 brakcet wiill empty and 3 wil content the value
from numpy import *
a=array([[[12,2],[20,30]],[[30,40],[50,60]],[[70,80],[90,100]]])
print(a[2,0:1])
a.ndim

[[70 80]]


3

In [31]:
import numpy
value=numpy.array([[[20,30]],[[40,50]]])
value.ndim
print(value)
value[1,0:2]

[[[20 30]]

 [[40 50]]]


array([[40, 50]])

In [1]:
from numpy import *
a=array([
    [                                 # this will be 9 dimetion
        [12,3,4,],                 # yeh 0 dimention ka 0 wala hai
        [12,3,4]                   # yeh 0 dimention ka 1 dimention hia
    ],
    [                                 # this will be 1 dimention
        [23,4,5],
        [10,20,30]
    ]
    
])

In [2]:
a[1,0,0:2]     # so 1 dimention ke andar ka 0m dimention ka 0 to 1 takh ka index ka values

array([23,  4])

In [7]:
import numpy
a=numpy.array([
    [
        [10,20],
        [30,40]
    ],
    [
        [100,200],
        [400,500]
    ]
])

In [10]:
print(a[0][1,0:1])  # this is how we select value in the numpy array

[30]


In [1]:
from numpy import *
a=array([
    [
    [2,3],
    [4,5]
    ],
    [
        [30,40],
        [50,60]
    ]
])

In [5]:
from numpy import *
a=array([
    [
        [10,20],
        [30,40]
    ],
    [
        [100,200],
        [300,400]
    ]
])

In [30]:
# finding the missing number from the list
def fa(arr,n):
    total=int((n+1)*(n+2)/2)
    print(total)
    for i in arr:
       # print(i) # in the arr variable all value is assign so ,in i  the value of list will be assign one by one
        total=total-i
    return total
a=[1,2,3,4,6,7,8]
#find the missing element
missing=fa(a,len(a))
print("the missing number from the list is ",missing)

36
the missing number from the list is  5


In [18]:
# this is used to count all the repeation of the element of the list
a=[1,2,3,4,3,3,4,2,5,5,2,3,4,5]
#repeation=set(a)  # first i will convert it into the set,so all the duplicate will get removes,now the loop will be run till this condition bec no repeation value is available
empty={}  # direct make a empty set,in which return the value
for i in a:
    empty[i]=a.count(i)
    #print(empty[i])  in this all value we get print,but at the end i had printed the  set which does not take duplicate ,so
print(empty)

{1: 1, 2: 3, 3: 4, 4: 3, 5: 3}


In [30]:
a=[1,2,3,5,6,7,8,9,10]
n=len(a) # the value of n must be the length of the list,tuple, dictionary
value=int((n+1)*(n+2)/2)
for i in a:
    #print(i)  i mai pura value aayega
    value=value-i
print(value)

4


In [31]:
# count total number of repeated number in list
a=[1,2,3,4,2,3,4,3,3]
ab={}
for i in a:
    ab[i]=a.count(i)
print(ab)

{1: 1, 2: 2, 3: 4, 4: 2}


In [48]:
# let see in the string how many time that paticular word is repeated
a="deepak is a good boy.deepak is a smart boy.deepak love driving"
for i in a:
    pass

In [2]:
import array  # but we know array cannot be multidimentional,so for that we wil use numpy
a=array.array('i',[1,2,3,4,5])


<class 'array.array'>


In [10]:
from numpy import *
a=array([[[1,2,3]]])
a.ndim

3

In [5]:
from array import array
a=array('i',[1,2,3,4,5])
b=array(a.typecode,[b for b in a])
b[1]=10
print(a)

array('i', [1, 2, 3, 4, 5])


In [7]:
b.reverse()

In [27]:
a="this is a string"
l=a.split(' ')  # when we split the string it wil convert it into the list,,.,string.split('bywhich')
print(type(l))

<class 'list'>


In [29]:
print(l)

['this', 'is', 'a', 'string']
4


In [5]:
cd={'a':{'b':10,20:40}}
cd['a'][20]

40