In [4]:
m=int(input("enter the number of rows"))
n=int(input("enter the number of column"))

def matrix(m,n):
    mat=[]
    for i in range(m):
        row=[]
        for j in range(n):
            value=int(input(f"mat[{i}][{j}]"))
            row.append(value) # bar bar row mai value add hotey rahyega,
        mat.append(row)  # us row ko append kar dia
    return mat


A=matrix(m,n)
print(A)
B=matrix(m,n)
print(B)

enter the number of rows2
enter the number of column3
mat[0][0]1
mat[0][1]2
mat[0][2]3
mat[1][0]4
mat[1][1]5
mat[1][2]6
[[1, 2, 3], [4, 5, 6]]
mat[0][0]1
mat[0][1]2
mat[0][2]3
mat[1][0]2
mat[1][1]3
mat[1][2]4


In [2]:
rows=int(input("enter how many rows u want :"))
column=int(input("enter how many column u want :"))
matrix=[]
for i in range(rows):
    val=[]
    for j in range(column):
        value=int(input(f"the value of matrix[{i},{j}]"))
        val.append(value)
    matrix.append(val)
print(matrix)


enter how many rows u want :2
enter how many column u want :2
the value of matrix[0,0]12
the value of matrix[0,1]2
the value of matrix[1,0]10
the value of matrix[1,1]1
[[12, 2], [10, 1]]


##### 

In [6]:
from numpy import *
A=[
    [1, 2, 4],
    [2,3,4]]
B=[
    [2 ,3],
    [1,2],
    [3,4]
]

In [21]:
a=[
    [0,0,0],
    [0,0,0]
]
for i in range(len(A)):
    for j in range(len(B[0])):  # this is main
        for k in range(len(B)):
            a[i][j]+=A[i][k]*B[k][j]
for result in a:
    print(result)

[16, 23, 0]
[19, 28, 0]


In [20]:
# Program to multiply two matrices using nested loops

# 3x3 matrix
X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]
# 3x4 matrix
Y = [[5,8,1,2],
    [6,7,3,0],
    [4,5,9,1]]
# result is 3x4
result = [[0,0,0,0],
         [0,0,0,0],
         [0,0,0,0]]
for i in range(len(X)):
    for j in range(len(Y[0])):  # this is main
        for k in range(len(Y)):
            result[i][j]+=X[i][k]*Y[k][j]
for r in result:
    print(r)

[114, 160, 60, 27]
[74, 97, 73, 14]
[119, 157, 112, 23]


In [22]:
a=[
    [1,2,3,4],
    [3,4,5,6]
]
print(a)

type(a)

[[1, 2, 3, 4], [3, 4, 5, 6]]


list

In [23]:
from numpy import *
ma=matrix(a)   # this is how we convert list to numpy
print(ma)
type(ma)

[[1 2 3 4]
 [3 4 5 6]]


numpy.matrix

In [1]:
from numpy import *
ab=matrix('1,2,3;4,5,6')  # formatig matrix
print(ab) 

[[1 2 3]
 [4 5 6]]


In [1]:
# this is how we create the matrix off number
n=int(input())
m=int(input())
mtrix=[]
for i in range(n):
    child=[]
    for j in range(m):
        value=int(input(f"the value enter in the matrix are[{i},{j}]"))  # that value you have to instake in the list
        child.append(value)
    mtrix.append(child)
for j in mtrix:
    print(j)

2
2
the value enter in the matrix are[0,0]2
the value enter in the matrix are[0,1]1
the value enter in the matrix are[1,0]2
the value enter in the matrix are[1,1]3
[2, 1]
[2, 3]


In [1]:
# making  3*3 matrix,3 rows,and 3 column
parent=[]
for i in range(3):
    child=[]  # this is very compulsory,ek ek karke pehle child waley array mai append karenge,and baad mai uske parent mai add karenge
    for j in range(3):
        value=int(input(f"the matrix vakue of {i},{j} is :"))
        child.append(value)
    parent.append(child)
print(parent)

the matrix vakue of 0,0 is :1
the matrix vakue of 0,1 is :2
the matrix vakue of 0,2 is :3
the matrix vakue of 1,0 is :4
the matrix vakue of 1,1 is :5
the matrix vakue of 1,2 is :6
the matrix vakue of 2,0 is :12
the matrix vakue of 2,1 is :13
the matrix vakue of 2,2 is :14
[[1, 2, 3], [4, 5, 6], [12, 13, 14]]


In [5]:
for i in parent:
    print(i)

[1, 2, 3]
[4, 5, 6]
[12, 13, 14]


In [3]:
n=int(input("enter the number of rows"))
m=int(input("enter the number of column"))
mat=[]
for i in range(n):
    small=[]
    for j in range(m):
        value=int(input(f"enter the value of matrix [{i},{j}] "))
        small.append(value)
    mat.append(small)

enter the number of rows2
enter the number of column3
enter the value of matrix [0,0] 12
enter the value of matrix [0,1] 1
enter the value of matrix [0,2] 2
enter the value of matrix [1,0] 2
enter the value of matrix [1,1] 3
enter the value of matrix [1,2] 2


In [4]:
print(mat)

[[12, 1, 2], [2, 3, 2]]
