In [20]:
# some basics example of dictionary
# : colon ke left wala keys and uske baad wala uski values
# comma is used to seprate the values
a={1:{'name':'deepak','age':23},2:{'surname':'khetwal'}}  # : ke baad wala colon ke pehle wala ke value hota hai
print(a[1]['name'])
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

deepak


In [41]:
#   >>>>>>    this is the example of nested dictionary <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
a={1:'deepak',2:"khetwal",3:{"name":"value"}}
print(a[3]['name'])

value


In [33]:
from numpy import *
a=array([1,2,4,5])
print(a)
b=a.copy()  # it is know as a deep copy,in this one is not dependt on another .
# b=a.view()    # it is knows as a shallow copy,this is dependent
print(b)
b[2]=100
print(a)
print(b)

[1 2 4 5]
[1 2 4 5]
[1 2 4 5]
[  1   2 100   5]


In [51]:
from numpy import *

a=array([
    [1,2,3],
    [4,5,6]
])
print(a)

[[1 2 3]
 [4 5 6]]


In [55]:
print(a[0][0:2])  # it mean a is a array [0] jiska 0 dimention ka value [0 sey 2 takh ] ka leyna hai


[1 2]


In [63]:
b=a.flatten()   # flatten is used to flat the array
print(b)
k=b.reshape(3,2)  # by making reshape we can make it array type
# first rows and 2 second column
print(k)

[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]


In [64]:
import numpy
zero=numpy.array(10)  # it is a zero dimentional array
zero.ndim

0

In [2]:
#  3 d array   : 3 d array is combo of 2D array 2d array
# in this all element must be present must be equals
from numpy import *
third=array([
    [[12,3,4],
        [23,4,5]],    
    [ [20,30,40],
        [50,50,20]]
])

print(third)
third.ndim
third[1,1,0:3]  # first 1 dimention ka 1 dimentionselect karke uska 0 sey 3 index takh kk=i values

[[[12  3  4]
  [23  4  5]]

 [[20 30 40]
  [50 50 20]]]


array([50, 50, 20])

In [80]:
#   2 d array
from numpy import *
arr=array([
    [23,43,5],[10,20,3]])
print(arr)
arr.ndim

[[23 43  5]
 [10 20  3]]


2

In [85]:
# slicing in 2d array
arr[0:2,0:2]  #  mean 0  sey leykar 1 dimentional ka , 0 sey leyker 1 index value deyna


array([[23, 43],
       [10, 20]])

In [2]:
from numpy import *
value=array([
    [
        [10,20,30],
        [40,50,60]
    ],
    [
        [40,50,70],
        [100,101,102]
    ]
])
value.ndim

3

In [5]:
value[0,0:2]  # as i have mentioned the 0 dimention element,fir 0 sey 2 takh ka dimention

array([[10, 20, 30],
       [40, 50, 60]])